ControlObras/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from usuarios.views import ingresar, salir, usuario_forbidden
from django.conf.urls.static import static
from django.conf import settings


if settings.DEBUG is True:
    urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    url(r'^admin/', include('usuarios.urls',namespace='usuarios',app_name="usuarios")),
    url(r'^admin2/', admin.site.urls),
    url(r'^login/$', ingresar, {'homepage':'vista:index'}, name='ingresar'),
    url(r'^logout/$', salir, name='salir'),
    url(r'^403/$', usuario_forbidden, name='forbidden'),
    url(r'^(?P<slug>[-\w\d]+)/ncr/',include('ncr.urls', namespace='ncr', app_name="ncr")),
    url(r'^(?P<slug>[-\w\d]+)/followup/',include('fu.urls', namespace='fu', app_name="fu")),
    url(r'^(?P<slug>[-\w\d]+)/dr/',include('dr.urls', namespace='dr', app_name="dr")),
    url(r'^',include('vista.urls', namespace='vista', app_name="vista")),
]

dr/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from dr import views

urlpatterns = [
    url(r'^editar/actividad/ajax', views.actividad_ajax, name='actividad_ajax'),
    url(r'^editar/composicion/ajax', views.composicion_ajax, name='composicion_ajax'),
    url(r'^editar/(?P<dr_id>[0-9]+)/actividad/composicion/agregar', views.composicion_agregar, name='composicion_agregar'),
    url(r'^editar/(?P<dr_id>[0-9]+)/ordenar', views.dr_ordenar, name='dr_ordenar'),
    url(r'^editar/(?P<dr_id>[0-9]+)/actividad/agregar', views.actividad_agregar, name='actividad_agregar'),
    url(r'^editar/(?P<dr_id>[0-9]+)/actividad/eliminar', views.actividad_eliminar, name='actividad_eliminar'),
    url(r'^editar/(?P<dr_id>[0-9]+)/composicion/eliminar', views.composicion_eliminar, name='composicion_eliminar'),
    url(r'^editar/(?P<dr_id>[0-9]+)', views.editar, name='editar'),
    url(r'^reporte/(?P<dr_id>[0-9]+)', views.create_dr_word, name='reporte_dr_word'),
    url(r'^listado', views.listado, name='listado'),
    url(r'^agregar', views.agregar, name='agregar'),
    url(r'^borrar', views.borrar, name='borrar'),
]

fu/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from fu import views

urlpatterns = [
    url(r'^avance', views.avance, name='avance'),
    url(r'^dashboard_diario', views.dashboard_diario, name='dashboard-diario'),
    url(r'^dashboard_imagen', views.dashboard_imagen, name='dashboard-imagen'),
    url(r'^dashboard', views.dashboard, name='dashboard'),
    url(r'^componentes', views.componente, name='componentes'),
    url(r'^actividades/registro/(?P<slug_ag>[-\w\d]+)', views.ingreso, name='ingreso'),
    url(r'^actividades/(?P<str_estado>[-\w\d]+)/ordenar', views.ordenar_actividades, name='actividades-ordenar'),
    url(r'^actividades', views.actividades, name='actividades'),
    url(r'^planificacion', views.planificacion, name='planificacion'),
    url(r'^configuracion', views.configuracion, name='configuracion'),
    url(r'^download_config', views.download_config, name='download_config'),
    url(r'^planificacion', views.planificacion, name='planificacion'),
    url(r'^paradas/agregar', views.add_paradas, name='agregar-paradas'),
    url(r'^paradas/(?P<id>[0-9]+)/editar', views.edit_paradas, name='editar-paradas'),
    url(r'^paradas', views.paradas, name='paradas'),
    url(r'^reportes', views.reportes, name='reportes'),
    url(r'^status_componentes', views.status_componentes, name='status_componentes'),
    # url(r'^componente/crear', views.create_componente, name='componente-create')
]

ncr/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from ncr import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^observaciones/(?P<slug_ag>[-\w\d]+)/listado_fotos', views.imagenes_aerogenerador, name='imagenes_aerogenerador'),
    url(r'^observaciones/resumen', views.observaciones_resumen, name='observaciones-resumen'),
    url(r'^observaciones/duplicadas', views.observaciones_duplicadas, name='observaciones_duplicadas'),
    url(r'^observaciones/imagenes/ver', views.list_fotos, name='fotos-list'),
    url(r'^observaciones/(?P<observacion_id>[0-9]+)/ver', views.show_observacion, name='observaciones-show'),
    url(r'^observaciones/(?P<observacion_id>[0-9]+)/editar', views.add_observacion, name='observaciones-editar'),
    url(r'^observaciones/(?P<observacion_id>[0-9]+)/revision/agregar', views.add_revision, name='revisiones-add'),
    url(r'^observaciones/(?P<observacion_id>[0-9]+)/revision/(?P<revision_id>[0-9]+)/editar', views.add_revision, name='revisiones-editar'),
    url(r'^observaciones/agregar', views.add_observacion, name='observaciones-agregar'),
    url(r'^observaciones/eliminar', views.del_observacion, name='observaciones-eliminar'),
    url(r'^observaciones/cerrar', views.close_observacion, name='observaciones-cerrar'),
    url(r'^observaciones/imagenes/set_primary', views.primary_image, name='imagenes-primary'),
    url(r'^observaciones/imagenes/set_orden', views.set_orden, name='imagenes-orden'),
    url(r'^observaciones/imagenes/(?P<image_id>[0-9]+)/borrar', views.del_image, name='imagenes-delete'),
    url(r'^revision/(?P<revision_id>[0-9]+)/imagenes/agregar', views.add_images, name='imagenes-agregar'),
    url(r'^revision/(?P<revision_id>[0-9]+)/imagenes/listado', views.table_fotos, name='imagenes-listado'),
    url(r'^revision/eliminar', views.del_revision, name='revision-eliminar'),
    url(r'^observaciones/informeNCR', views.informe_ncr, name='informeNCR'),
    url(r'^observaciones/punchlist', views.punchlist, name='punchlist'),
    url(r'^observaciones/(?P<slug_ag>[-\w\d]+)', views.observaciones, name='observaciones'),
    url(r'^observadores', views.observadores, name='observadores'),
    url(r'^configuracion', views.configuracion, name='configuracion')

]

fu/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
from django.db import models
from vista.models import ParqueSolar,Aerogenerador
from django.contrib.auth.models import User
import datetime

import logging
logger = logging.getLogger('oritec')


@python_2_unicode_compatible
class EstadoFU(models.Model):
    nombre = models.CharField(max_length=100, unique=True)
    idx = models.IntegerField(unique=True)
    orden = models.IntegerField(default=0)

    def __str__(self):
        return '%s' % self.nombre


@python_2_unicode_compatible
class SectorObraElectrica(models.Model):
    nombre = models.CharField(max_length=100, unique=True)
    idx = models.IntegerField(unique=True)
    orden = models.IntegerField(default=0)

    def __str__(self):
        return '%s' % self.nombre


@python_2_unicode_compatible
class ComponenteObraElectrica(models.Model):
    nombre = models.CharField(max_length=100, unique=True)
    sectores = models.ManyToManyField(SectorObraElectrica)

    def __str__(self):
        return '%s' % self.nombre


@python_2_unicode_compatible
class Componente(models.Model):
    nombre = models.CharField(max_length=100, unique=True)
    estados = models.ManyToManyField(EstadoFU)

    def __str__(self):
        return '%s' % self.nombre


@python_2_unicode_compatible
class ComponentesParque(models.Model):
    parque = models.OneToOneField(ParqueSolar, on_delete=models.CASCADE)
    componentes = models.ManyToManyField(Componente,
                                         through='RelacionesFU', through_fields=('componentes_parque', 'componente'))

    def __str__(self):
        return 'Componentes Parque ' + '%s' % self.parque.nombre


# Hay un evidente problema de nombre. ParqueSolar es un legacy name, que no tiene significado.
@python_2_unicode_compatible
class ParqueEolico(models.Model):
    parque = models.ForeignKey(ParqueSolar, on_delete=models.CASCADE)
    componentes = models.ManyToManyField(Componente, through='Membership', related_name='members')
    componentes_obraelectrica = models.ManyToManyField(ComponenteObraElectrica,
                                                       through='MembershipObraElectrica',
                                                       related_name='members_electricos')

    def __str__(self):
        return 'Componentes Parque Eolico' + '%s' % self.parque.nombre


@python_2_unicode_compatible
class Membership(models.Model):
    parque_eolico = models.ForeignKey(ParqueEolico, on_delete=models.CASCADE)
    componente = models.ForeignKey(Componente, on_delete=models.CASCADE)
    estado = models.ForeignKey(EstadoFU, on_delete=models.CASCADE)
    orden = models.SmallIntegerField()

    class Meta:
        unique_together = ("parque_eolico", "componente", "estado")

    def __str__(self):
        return 'Relacion Componente - Parque ' + '%s-%s' % (self.parque_eolico, self.componente.nombre)

    def save(self, *args, **kwargs):
        if self.pk is None:
            aux = Membership.objects.filter(parque_eolico=self.parque_eolico, estado=self.estado).order_by('-orden')
            if aux.count() == 0:
                self.orden = 1
            else:
                last = aux[0]
                self.orden = last.orden + 1
        super(Membership, self).save()


@python_2_unicode_compatible
class MembershipObraElectrica(models.Model):
    parque_eolico = models.ForeignKey(ParqueEolico, on_delete=models.CASCADE)
    componente = models.ForeignKey(ComponenteObraElectrica, on_delete=models.CASCADE)
    sector = models.ForeignKey(SectorObraElectrica, on_delete=models.CASCADE)
    orden = models.SmallIntegerField()

    class Meta:
        unique_together = ("parque_eolico", "componente", "sector")

    def __str__(self):
        return 'Relacion Componente - Parque ' + '%s-%s' % (self.parque_eolico, self.componente.nombre)

    def save(self, *args, **kwargs):
        if self.pk is None:
            aux = MembershipObraElectrica.objects.filter(parque_eolico=self.parque_eolico,
                                                         sector=self.sector).order_by('-orden')
            if aux.count() == 0:
                self.orden = 1
            else:
                last = aux[0]
                self.orden = last.orden + 1
        super(MembershipObraElectrica, self).save()


@python_2_unicode_compatible
class RelacionesFU(models.Model):
    componentes_parque = models.ForeignKey(ComponentesParque, on_delete=models.CASCADE)
    componente = models.ForeignKey(Componente, on_delete=models.CASCADE)
    orden_descarga = models.SmallIntegerField()
    orden_premontaje = models.SmallIntegerField()
    orden_montaje = models.SmallIntegerField()
    orden_puestaenmarcha = models.SmallIntegerField()

    class Meta:
        unique_together = ("componentes_parque", "componente")

    def __str__(self):
        return 'Relaciones Componentes Parque ' + '%s' % self.componentes_parque.parque.nombre


def plan_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'planificacion/{0}'.format(filename)


@python_2_unicode_compatible
class ConfiguracionFU(models.Model):
    parque = models.OneToOneField('vista.ParqueSolar', on_delete=models.CASCADE)
    fecha_inicio = models.DateField(blank=False, null=False)
    fecha_final = models.DateField(blank=False, null=False)
    plan = models.FileField(upload_to=plan_directory_path, max_length=500, null=True, blank=True)
    prev_plan = models.FileField(upload_to=plan_directory_path, max_length=500, null=True, blank=True)
    componente_montaje = models.ForeignKey(Componente, null=True, default=None, blank=True, on_delete=models.SET_NULL)
    obras_civiles = models.BooleanField(default=True)
    caminos = models.BooleanField(default=True)
    obras_electricas = models.BooleanField(default=True)
    no_vistas = models.IntegerField(default=0)

    def __str__(self):
        return 'Configuracion'

    def save(self, *args, **kwargs):
        if self.plan:
            self.prev_plan = self.__class__._default_manager.filter(pk=self.pk).values('plan').get()['plan']
        super(ConfiguracionFU, self).save(*args, **kwargs)  # Call the "real" save() method.


@python_2_unicode_compatible
class Plan(models.Model):
    parque = models.ForeignKey(ParqueSolar, on_delete=models.CASCADE)
    componente = models.ForeignKey(Componente, on_delete=models.CASCADE)
    estado = models.ForeignKey(EstadoFU, on_delete=models.CASCADE)
    fecha = models.DateField(blank=False, null=False)
    no_aerogeneradores = models.SmallIntegerField()

    class Meta:
        unique_together = ("parque", "componente" ,"estado", "fecha")

    def __str__(self):
        return 'Plan, parque='+self.parque.nombre+',componente='+self.componente.nombre+',estado='+self.estado.nombre+\
               ',nº de aerogeneradores='+str(self.no_aerogeneradores)


@python_2_unicode_compatible
class Contractual(models.Model):
    parque = models.ForeignKey(ParqueSolar, on_delete=models.CASCADE)
    componente = models.ForeignKey(Componente, on_delete=models.CASCADE)
    estado = models.ForeignKey(EstadoFU, on_delete=models.CASCADE)
    fecha = models.DateField(blank=False, null=False)
    no_aerogeneradores = models.SmallIntegerField()

    class Meta:
        unique_together = ("parque", "componente", "estado", "fecha")

    def __str__(self):
        return 'Contractual, parque=' + \
               self.parque.nombre + \
               ',componente=' + self.componente.nombre + ',estado=' + self.estado.nombre + \
               ',nº de aerogeneradores=' + str(self.no_aerogeneradores)


@python_2_unicode_compatible
class PlanObrasElectricas(models.Model):
    parque = models.ForeignKey(ParqueSolar, on_delete=models.CASCADE)
    componente = models.ForeignKey(ComponenteObraElectrica, on_delete=models.CASCADE)
    sector = models.ForeignKey(SectorObraElectrica, on_delete=models.CASCADE)
    fecha = models.DateField(blank=False, null=False)
    avance = models.FloatField()

    class Meta:
        unique_together = ("parque", "componente", "sector", "fecha")

    def __str__(self):
        return 'Plan Obras Civiles, parque=' + self.parque.nombre + \
               ',componente=' + self.componente.nombre + \
               ',sector=' + self.sector.nombre + \
               ',avance=' + str(self.avance)


@python_2_unicode_compatible
class ContractualObrasElectricas(models.Model):
    parque = models.ForeignKey(ParqueSolar, on_delete=models.CASCADE)
    componente = models.ForeignKey(ComponenteObraElectrica, on_delete=models.CASCADE)
    sector = models.ForeignKey(SectorObraElectrica, on_delete=models.CASCADE)
    fecha = models.DateField(blank=False, null=False)
    avance = models.FloatField()

    class Meta:
        unique_together = ("parque", "componente", "sector", "fecha")

    def __str__(self):
        return 'Contractual Obras Civiles, parque=' + self.parque.nombre + \
               ',componente=' + self.componente.nombre + \
               ',sector=' + self.sector.nombre + \
               ',avance=' + str(self.avance)


@python_2_unicode_compatible
class Registros(models.Model):
    parque = models.ForeignKey(ParqueSolar, on_delete=models.CASCADE)
    aerogenerador = models.ForeignKey(Aerogenerador, on_delete=models.CASCADE)
    componente = models.ForeignKey(Componente, on_delete=models.CASCADE)
    estado = models.ForeignKey(EstadoFU, on_delete=models.CASCADE)
    fecha = models.DateField(blank=False, null=False)
    no_serie = models.CharField(max_length=100, unique=False, blank=False, null=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    class Meta:
        unique_together = ("parque", "aerogenerador", "componente", "estado")

    def __str__(self):
        return 'Registro, parque=' + self.parque.nombre + ',aerogenerador=' + self.aerogenerador.nombre + \

fu/templates/fu/actividades.html
{% extends "base.html" %}
{% load staticfiles %}
{% load customtags %}
{% load tz %}
{% block css %}
    <!-- BEGIN PAGE LEVEL STYLES -->
    <link href="{% static 'common/assets/global/plugins/datatables/datatables.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'common/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'common/assets/global/plugins/bootstrap-select/css/bootstrap-select.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'common/assets/global/plugins/jquery-nestable/jquery.nestable.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'common/assets/global/plugins/select2/css/select2.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'common/assets/global/plugins/select2/css/select2-bootstrap.min.css' %}" rel="stylesheet" type="text/css" />

    <!-- END PAGE LEVEL STYLES -->
{% endblock %}

{% block contenido %}


    {% if parque.no_aerogeneradores == 0 %}
        <div class="row">
            <div class="col-md-11 col-md-offset-1">
                <h4>Por favor, ingresar la informaci&oacute;n del parque (Configuraci&oacute;n).</h4>
            </div>
        </div>
    {%  else %}
        <div class="row">
            <div class="col-md-12">
                <input type="button" id="add_componente" data-target="#basic" data-toggle="modal" class="btn btn-sm green-steel" value="Agregar Componente a Proyecto" onclick="addComponente('{% url 'fu:status_componentes' parque.slug %}');"/>
                <input type="button" id="del_componente" data-target="#delete" data-toggle="modal" class="btn btn-sm red-soft" value="Eliminar Componente de Proyecto"/>
            </div>
        </div>
        <p></p>
        <div class="row">
            {% for e, lista in actividades.items %}
                <div class="col-md-{{ actividades|get_column_width }}">
                    <div class="panel panel-default" style="margin-bottom: 10px;">
                        <div class="panel-heading">
                            <h3 class="panel-title">{{ titulos|get_item:e }}</h3>
                        </div>
                        <div class="panel-body">
                            {% if lista %}
                                <div class="dd" id="nestable-{{ e }}">
                                    <ol class="dd-list">
                                        {% for k, l in lista.items %}
                                            <li class="dd-item" data-id="{{ k }}">
                                                <div class="dd-handle">{{ l }}</div>
                                            </li>
                                        {% endfor %}
                                    </ol>
                                </div>
                            {% else %}
                                Sin componentes.
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}

        </div>

    {% endif %}

    <div class="modal fade bs-modal-lg" id="basic" tabindex="-1" role="basic" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                    <h4 class="modal-title">
                        <span class="glyphicon glyphicon-plus" style="color:rgba(74,182,100,0.89);font-size:20px"></span>
                        <b>Agregar Componente</b> </h4>
                </div>
                <form action="{% url 'fu:actividades' parque.slug %}" method="post" id="formModal" class="horizontal-form">
                    {% csrf_token %}
                    <div class="modal-body">
                        <div class="form-body">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label">{{ choicesComponentesForm.componente.label }}:</label>
                                        {{ choicesComponentesForm.componente }}
                                        <span class="help-block"> {{ choicesComponentesForm.componente.errors }} </span>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group form-md-checkboxes">
                                        <label style="color: #333333;">Estados posibles:</label>
                                        <div class="md-checkbox-list">
                                            {% for choice in choicesComponentesForm.estadofu %}
                                                <div class="md-checkbox">
                                                    {{ choice.tag }}
                                                    <label for="{{ choice.id_for_label }}">
                                                        <span></span>
                                                        <span class="check"></span>
                                                        <span class="box"></span> {{ choice.choice_label }}
                                                    </label>
                                                </div>
                                            {% endfor %}
                                        </div>
                                        <span class="help-block"> {{ choicesComponentesForm.estadofu.errors }} </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn default" data-dismiss="modal" onclick="cancelComponente()">Cancelar</button>
                        <button type="submit" id='enviarmodal' class="btn green" name="addComponente">Agregar</button>
                        <!--<a href="" id='enviarmodal' class="btn btn-success success">Save Changes</a>-->
                        <!--<button type="button" id="enviarmodal" class="btn blue">Save changes</button>-->
                    </div>
                </form>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>

    <div class="modal fade bs-modal-lg" id="delete" tabindex="-1" role="basic" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                    <h4 class="modal-title">
                        <span class="glyphicon glyphicon-remove-sign" style="color:rgba(244,52,42,0.89);font-size:20px"></span>
                        <b>Eliminar Componente</b> </h4>
                </div>
                <div class="modal-body">
                    <form action="{% url 'fu:actividades' parque.slug %}" method="post" id="formModal" class="horizontal-form">
                        {% csrf_token %}
                        <div class="form-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="control-label">{{ deleteComponentesForm.componente.label }}:</label>
                                        {{ deleteComponentesForm.componente }}
                                        <span class="help-block"> {{ deleteComponentesForm.componente.errors }} </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn default" data-dismiss="modal">Cancelar</button>
                    <button type="submit" id='enviarmodal' class="btn green" name="delComponente">Eliminar</button>
                    <!--<a href="" id='enviarmodal' class="btn btn-success success">Save Changes</a>-->
                    </form>
                    <!--<button type="button" id="enviarmodal" class="btn blue">Save changes</button>-->

                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>


{% endblock %}

{% block javascript %}
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <script src="{% static 'common/assets/global/scripts/datatable.js' %}" type="text/javascript"></script>
    <script src="{% static 'common/assets/global/plugins/datatables/datatables.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'common/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js' %}" type="text/javascript"></script>
    <script src="{% static 'common/assets/global/plugins/jquery-multi-select/js/jquery.multi-select.js' %}" type="text/javascript"></script>
    <script src="{% static 'common/assets/global/plugins/bootstrap-select/js/bootstrap-select.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'common/assets/global/plugins/jquery-nestable/jquery.nestable.js' %}" type="text/javascript"></script>
    <script src="{% static 'common/select2/js/select2.full.min.js' %}" type="text/javascript"></script>

    <script src="{% static 'common/js/tabla-componentes.js' %}" type="text/javascript"></script>
    <script src="{% static 'common/js/actividades.js' %}" type="text/javascript"></script>

    <script type="text/javascript">
        function editModal(id,nombre,options){
            console.log('click, id=' + id + ', nombre='+nombre);
            $('#formModal').append('<input type="hidden" name="id" id="componente_id" value="' + id + '">');
            $('#id_nombre').val(nombre);
            console.log('[value=' + options.join('], [value=') + ']');
            for (var i = 0; i < options.length; i++) {
                console.log($("[nombre='estadofu'] ,[value="+options[i]+"]"));
                $("[nombre=estadofu] [value="+options[i]+"]").prop("checked", true);
            }
            $('#basic').modal();
        };
    </script>
    <!-- END PAGE LEVEL PLUGINS -->
{% endblock %}



{% block jquery %}

    function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    $.ajaxSetup({
    beforeSend: function(xhr, settings) {
    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
    var csrftoken = Cookies.get('csrftoken');
    xhr.setRequestHeader("X-CSRFToken", csrftoken);
    }
    }
    });

    $('.bs-select').selectpicker({
    iconBase: 'fa',
    tickIcon: 'fa-check',
    dropupAuto: false,
    liveSearch: true,
    });

    $('#id_componente').css('width', '100%');


    {% for e, lista in actividades.items %}
        $('#nestable-{{ e }}').nestable({
        maxDepth:1,
        group:1,
        }).on('change', function() {
        s=$(this).nestable('serialize');
        console.log(s);
        $.ajax({
        // Uncomment the following to send cross-domain cookies:
        //xhrFields: {withCredentials: true},
        url: "{% url 'fu:actividades-ordenar' parque.slug  e %}",
        type: 'POST',
        dataType: 'json',
        data: {
        'lista' : s,
        },
        //context: $('#fileupload')[0]
        }).success(function (result) {
        console.log("Pulento");
        }).fail(function( jqXHR, textStatus ) {
        console.log( "Request failed: " + textStatus );
        });
        });
    {% endfor %}

{% endblock %}

fu/templates/fu/aerogeneradores.html
{% load staticfiles %}
{% load customtags %}
{% for ag, valores in pos_ag.items %}{% if valores.img %}
<div id="{{ ag }}" name="agen" style="position: absolute; z-index: {{ valores|get_item:'zindex'|safe }}; width:{{ valores|get_item:'width'|safe }}%; top: {{ valores|get_item:'top'|safe }}%; left: {{ valores|get_item:'left'|safe }}%;">
    <a href="{{ valores|get_item:'url' }}"><img class="img-responsive" src="{% static valores|get_item:'img' %}" ></a>
</div>
{% endif %}{% endfor %}

fu/templates/fu/avance.html
{% extends "base.html" %}
{% load staticfiles %}
{% load customtags %}
{% load tz %}
{% block css %}
    <!-- BEGIN PAGE LEVEL STYLES -->
    <link rel="stylesheet" type="text/css" href="{% static 'common/css/Litetooltip/litetooltip.css' %}"/>
    <!-- END PAGE LEVEL STYLES -->
    <style>
        .bootstrap-datetimepicker-widget tr:hover {
            background-color: #808080;
        }
        .dashboard-stat.dashboard-stat-v2 .visual {
            padding-top: 15px;
            margin-bottom: 20px;
        }
        #ampliar {
            cursor: pointer;
        }

        #tooltip {
            text-align:center;
            background:black;
            color:white;
            padding:3px 0;
            width:120px;
            position:fixed;
            display:none;
            white-space:nowrap;
            z-index:500;
        }

    </style>
{% endblock %}

{% block contenido %}
    <div class="row" >
        <div class="col-md-12" id="fila">
            <div class="imagehotspot-container" style="position: relative; max-width: 1280px; /* max-width: actual width of image */ width: 100%; height: auto; z-index: 101;">
                <div style="position: relative; height: 0px; padding-bottom: 81.17%; /* padding-bottom: image's height divided by width multiply by 100 */">
                    <img class="img-responsive" id="plano" src="{% static '/common/images/plano2.png' %}" style="position: absolute; top: 0px; left: 0px; z-index: 102">
                </div>
                {% include "fu/aerogeneradores.html" %}
            </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
<!-- BEGIN PAGE LEVEL PLUGINS -->
    <script type="text/javascript" src="{% static 'common/js/Litetooltip/litetooltip.js' %}"></script>
<!-- END PAGE LEVEL PLUGINS -->
{% endblock %}

{% block jquery %}

{% endblock %}