ControlObras/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from usuarios.views import ingresar, salir, usuario_forbidden
from django.conf.urls.static import static
from django.conf import settings


if settings.DEBUG is True:
    urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    url(r'^admin/', include('usuarios.urls',namespace='usuarios',app_name="usuarios")),
    url(r'^admin2/', admin.site.urls),
    url(r'^login/$', ingresar, {'homepage':'vista:index'}, name='ingresar'),
    url(r'^logout/$', salir, name='salir'),
    url(r'^403/$', usuario_forbidden, name='forbidden'),
    url(r'^(?P<slug>[-\w\d]+)/ncr/',include('ncr.urls', namespace='ncr', app_name="ncr")),
    url(r'^(?P<slug>[-\w\d]+)/followup/',include('fu.urls', namespace='fu', app_name="fu")),
    url(r'^(?P<slug>[-\w\d]+)/dr/',include('dr.urls', namespace='dr', app_name="dr")),
    url(r'^',include('vista.urls', namespace='vista', app_name="vista")),
]

dr/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from dr import views

urlpatterns = [
    url(r'^editar/actividad/ajax', views.actividad_ajax, name='actividad_ajax'),
    url(r'^editar/composicion/ajax', views.composicion_ajax, name='composicion_ajax'),
    url(r'^editar/(?P<dr_id>[0-9]+)/actividad/composicion/agregar', views.composicion_agregar, name='composicion_agregar'),
    url(r'^editar/(?P<dr_id>[0-9]+)/ordenar', views.dr_ordenar, name='dr_ordenar'),
    url(r'^editar/(?P<dr_id>[0-9]+)/actividad/agregar', views.actividad_agregar, name='actividad_agregar'),
    url(r'^editar/(?P<dr_id>[0-9]+)/actividad/eliminar', views.actividad_eliminar, name='actividad_eliminar'),
    url(r'^editar/(?P<dr_id>[0-9]+)/composicion/eliminar', views.composicion_eliminar, name='composicion_eliminar'),
    url(r'^editar/(?P<dr_id>[0-9]+)', views.editar, name='editar'),
    url(r'^reporte/(?P<dr_id>[0-9]+)', views.create_dr_word, name='reporte_dr_word'),
    url(r'^listado', views.listado, name='listado'),
    url(r'^agregar', views.agregar, name='agregar'),
    url(r'^borrar', views.borrar, name='borrar'),
]

dr/forms.py
# -*- coding: utf-8 -*-
from django import forms
from dr.models import DR
import logging
from datetime import date
logger = logging.getLogger('oritec')

class DRForm(forms.ModelForm):
    fecha = forms.DateField(widget=forms.DateInput(format='%d-%m-%Y'),
                                        input_formats=('%d-%m-%Y',))

    class Meta:
        model = DR
        fields = ['parque','fecha', 'numero', 'climatologia','sitio','actividades', 'hora_entrada', 'hora_salida']
        labels = {
            'actividades': 'Actividades Principales',
            'numero': 'Número',
        }

    def __init__(self, *args, **kwargs):
        super(DRForm, self).__init__(*args, **kwargs)
        self.fields['parque'].widget = forms.HiddenInput()
        self.fields['fecha'].widget.attrs['class'] = 'form-control'
        self.fields['fecha'].widget.attrs['readonly'] = True
        self.fields['numero'].widget.attrs['class'] = 'form-control'
        self.fields['climatologia'].widget.attrs['class'] = 'form-control'
        self.fields['sitio'].widget.attrs['class'] = 'form-control'
        self.fields['actividades'].widget.attrs['class'] = 'form-control'
        self.fields['hora_entrada'].widget.attrs['class'] = 'form-control timepicker'
        self.fields['hora_salida'].widget.attrs['class'] = 'form-control timepicker'

ncr/forms.py
# -*- coding: utf-8 -*-
from django import forms
from ncr.models import Observacion, Revision,EstadoRevision,Severidad,Componente,Subcomponente,Tipo, Prioridad
from vista.models import ParqueSolar,Aerogenerador
from fu.models import ConfiguracionFU
import logging
from datetime import date
logger = logging.getLogger('oritec')

class ObservacionForm(forms.ModelForm):
    fecha_observacion = forms.DateField(widget=forms.DateInput(format = '%d-%m-%Y'),
                                 input_formats=('%d-%m-%Y',))
    class Meta:
        model = Observacion
        fields = ['parque','nombre','aerogenerador','fecha_observacion','componente','sub_componente','tipo',
                  'punchlist','reported_by','clase','no_serie']
        labels = {
            'nombre': 'Descripción',
            'reported_by': 'Reportado por',
            'no_serie': 'Número de Serie',
            'clase': 'Categoría',
            'fecha_observacion': 'Fecha observación'
        }
    def __init__(self, *args, **kwargs):
        super(ObservacionForm, self).__init__(*args, **kwargs)
        if 'initial' in kwargs:
            parque = kwargs['initial']['parque']
            self.fields['aerogenerador'].queryset = Aerogenerador.objects.filter(parque=parque)
        elif 'instance' in kwargs:
            parque = kwargs['instance'].parque
            self.fields['aerogenerador'].queryset = Aerogenerador.objects.filter(parque=parque)
        #parque = kwargs['initial']['parque']
        #opciones = []
        #for ag in range(1,parque.no_aerogeneradores+1):
            #logger.debug(ag)
        #    opciones.append((ag,'WTG'+str(ag).zfill(2)))
        #self.fields['aerogenerador'] = forms.ChoiceField(
        #    choices=opciones
        #)
        self.fields['componente'].queryset = self.fields['componente'].queryset.order_by('orden_punchlist')
        self.fields['sub_componente'].queryset = self.fields['sub_componente'].queryset.order_by('orden_punchlist')
        self.fields['tipo'].queryset = self.fields['tipo'].queryset.order_by('orden_punchlist')
        self.fields['parque'].widget = forms.HiddenInput()
        self.fields['aerogenerador'].widget.attrs['class'] = 'bs-select form-control'
        self.fields['aerogenerador'].widget.attrs['data-live-search'] = 'true'
        self.fields['aerogenerador'].widget.attrs['data-size'] = '8'
        self.fields['nombre'].widget.attrs['class'] = 'form-control'
        self.fields['aerogenerador'].widget.attrs['class'] = 'bs-select form-control'
        self.fields['fecha_observacion'].widget.attrs['class'] = 'form-control'
        self.fields['fecha_observacion'].widget.attrs['readonly'] = True
        self.fields['componente'].widget.attrs['class'] = 'bs-select form-control'
        self.fields['componente'].widget.attrs['data-live-search'] = 'true'
        self.fields['componente'].widget.attrs['data-size'] = '8'
        self.fields['sub_componente'].widget.attrs['class'] = 'bs-select form-control'
        self.fields['sub_componente'].widget.attrs['data-live-search'] = 'true'
        self.fields['sub_componente'].widget.attrs['data-size'] = '8'
        self.fields['no_serie'].widget.attrs['class'] = 'form-control'
        self.fields['tipo'].widget.attrs['class'] = 'bs-select form-control'
        self.fields['tipo'].widget.attrs['data-live-search'] = 'true'
        self.fields['tipo'].widget.attrs['data-size'] = '8'
        self.fields['punchlist'].widget.attrs['class'] = 'make-switch'
        self.fields['punchlist'].widget.attrs['data-size'] = 'small'
        self.fields['punchlist'].widget.attrs['data-on-text'] = 'Si'
        self.fields['punchlist'].widget.attrs['data-off-text'] = 'No'
        self.fields['punchlist'].widget.attrs['checked'] = ''
        self.fields['clase'].widget.attrs['class'] = 'make-switch'
        self.fields['clase'].widget.attrs['data-size'] = 'small'
        self.fields['clase'].widget.attrs['data-on-text'] = 'NCR'
        self.fields['clase'].widget.attrs['data-off-text'] = 'Sin Categoría'
        self.fields['reported_by'].widget.attrs['class'] = 'bs-select form-control'
        self.fields['reported_by'].widget.attrs['data-live-search'] = 'true'
        self.fields['reported_by'].widget.attrs['data-size'] = '8'

class RevisionForm(forms.ModelForm):
    fecha_revision = forms.DateField(widget=forms.HiddenInput(),
                                        input_formats=('%d-%m-%Y',))
    class Meta:
        model = Revision
        fields = ['fecha_revision','severidad','prioridad','nombre','descripcion']
        labels = {
            'nombre': 'Descripción',
            'descripcion': 'Detalle',
        }
    def __init__(self, *args, **kwargs):
        super(RevisionForm, self).__init__(*args, **kwargs)
        #self.fields['fecha_revision'].widget = forms.HiddenInput()
        self.fields['severidad'].widget.attrs['class'] = 'bs-select form-control'
        self.fields['severidad'].widget.attrs['data-live-search'] = 'true'
        self.fields['prioridad'].widget.attrs['class'] = 'bs-select form-control'
        self.fields['prioridad'].widget.attrs['data-size'] = '8'
        self.fields['nombre'].widget.attrs['class'] = 'form-control'
        self.fields['descripcion'].widget = forms.Textarea()
        self.fields['descripcion'].widget.attrs['class'] = 'form-control'
        self.fields['descripcion'].widget.attrs['row'] = '3'

class RevisionFormFull(forms.ModelForm):
    fecha_revision = forms.DateField(widget=forms.DateInput(format = '%d-%m-%Y'),
                                 input_formats=('%d-%m-%Y',))
    class Meta:
        model = Revision
        fields = ['observacion','fecha_revision','severidad','prioridad','nombre','descripcion', 'estado','reported_by']
        labels = {
            'nombre': 'Descripción',
            'fecha_revision' : 'Fecha revisión',
            'descripcion': 'Detalle',
            'reported_by': 'Reportado por'
        }
    def __init__(self, *args, **kwargs):
        super(RevisionFormFull, self).__init__(*args, **kwargs)
        self.fields['observacion'].widget = forms.HiddenInput()
        self.fields['severidad'].widget.attrs['class'] = 'bs-select form-control'
        self.fields['severidad'].widget.attrs['data-live-search'] = 'true'
        self.fields['severidad'].widget.attrs['data-size'] = '8'
        self.fields['prioridad'].widget.attrs['class'] = 'bs-select form-control'
        self.fields['descripcion'].widget = forms.Textarea()
        self.fields['descripcion'].widget.attrs['class'] = 'form-control'
        self.fields['descripcion'].widget.attrs['row'] = '3'
        self.fields['fecha_revision'].widget.attrs['class'] = 'form-control'
        self.fields['estado'].widget.attrs['class'] = 'bs-select form-control'
        self.fields['reported_by'].widget.attrs['class'] = 'bs-select form-control'
        self.fields['reported_by'].widget.attrs['data-live-search'] = 'true'
        self.fields['reported_by'].widget.attrs['data-size'] = '8'
        self.fields['nombre'].widget.attrs['class'] = 'form-control'

class NCR(forms.Form):
    aerogenerador = forms.ModelMultipleChoiceField(queryset=Aerogenerador.objects.all(),required=False)
    condicion = forms.MultipleChoiceField(choices=[('reparadas', 'Cerrada'), ('no reparadas', 'Abierta')],required=False,label="Condición")
    estado = forms.ModelMultipleChoiceField(queryset=EstadoRevision.objects.all(),required=False)
    severidad = forms.ModelMultipleChoiceField(queryset=Severidad.objects.all(),required=False)
    prioridad = forms.ModelMultipleChoiceField(queryset=Prioridad.objects.all(), required=False)
    componente = forms.ModelMultipleChoiceField(queryset=Componente.objects.all().order_by('orden_punchlist'),required=False)
    subcomponente = forms.ModelMultipleChoiceField(queryset=Subcomponente.objects.all().order_by('orden_punchlist'),required=False)
    tipo = forms.ModelMultipleChoiceField(queryset=Tipo.objects.all().order_by('orden_punchlist'),required=False)
    clase = forms.MultipleChoiceField(choices=[('1', 'NCR'), ('0', 'Incidencia')],
                                          required=False, label="Categoría")
    punchlist = forms.MultipleChoiceField(choices=[('0', 'No'), ('1', 'Si')],
                                          required=False, label="Punchlist")
    fecha_from = forms.DateField(widget=forms.DateInput(format='%d-%m-%Y'), input_formats=('%d-%m-%Y',), initial=date.today)
    fecha_to = forms.DateField(widget=forms.DateInput(format='%d-%m-%Y'), input_formats=('%d-%m-%Y',), initial=date.today)
    def __init__(self, *args, **kwargs):
        parque = kwargs.pop('parque')
        super(NCR, self).__init__(*args, **kwargs)
        try:
            obj = ConfiguracionFU.objects.get(parque=parque)
            self.fields['fecha_from'].initial = obj.fecha_inicio
        except ConfiguracionFU.DoesNotExist:
            logger.debug("ConfiguracionFU para parque no existe, queda todo igual")
        self.fields['aerogenerador'].queryset = Aerogenerador.objects.filter(parque=parque).order_by('idx')
        self.fields['fecha_from'].widget.attrs['class'] = 'form-control'
        self.fields['fecha_from'].widget.attrs['readonly'] = True
        self.fields['fecha_to'].widget.attrs['class'] = 'form-control'
        self.fields['fecha_to'].widget.attrs['readonly'] = True

#        self.fields['aerogenerador'].widget.attrs['class'] = 'form-control'

class DuplicarObservacionForm(forms.Form):
    aerogenerador = forms.ModelMultipleChoiceField(queryset=Aerogenerador.objects.all(),required=False)
    def __init__(self, *args, **kwargs):
        parque = kwargs.pop('parque')
        super(DuplicarObservacionForm, self).__init__(*args, **kwargs)
        self.fields['aerogenerador'].queryset = Aerogenerador.objects.filter(parque=parque).order_by('idx')

class Punchlist(forms.Form):
    aerogenerador = forms.ModelMultipleChoiceField(queryset=Aerogenerador.objects.all().order_by('idx'),required=False)

dr/templates/dr/agregar.html
{% extends "base.html" %}
{% load staticfiles %}
{% load customtags %}
{% load tz %}
{% load sekizai_tags %}


{% block contenido %}
    {% if parque.no_aerogeneradores == 0 %}
        <div class="row">
            <div class="col-md-11 col-md-offset-1">
                <h4>Por favor, ingresar la informaci&oacute;n del parque (Configuraci&oacute;n).</h4>
            </div>
        </div>
    {%  else %}
        <div class="row">
            <div class="portlet box blue" style="margin-left:30px;margin-right:30px;">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-search"></i> Agregar DR
                    </div>
                </div>
                <div class="portlet-body form">
                    <!-- BEGIN FORM-->
                    {% include "dr/w_dr_form.html" %}
                </div>
            </div>
        </div>

    {% endif %}
{% endblock %}

dr/templates/dr/agregar2.html
{% extends "base.html" %}
{% load staticfiles %}
{% load customtags %}
{% load tz %}
{% load sekizai_tags %}


{% block contenido %}
    {% if parque.no_aerogeneradores == 0 %}
        <div class="row">
            <div class="col-md-11 col-md-offset-1">
                <h4>Por favor, ingresar la informaci&oacute;n del parque (Configuraci&oacute;n).</h4>
            </div>
        </div>
    {%  else %}
        <div class="row">
            <div class="portlet box blue" style="margin-left:30px;margin-right:30px;">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-search"></i> Agregar DR
                    </div>
                </div>
                <div class="portlet-body form">
                    <!-- BEGIN FORM-->
                    {% include "dr/w_dr_form.html" %}
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

dr/templates/dr/listado.html
{% extends "base.html" %}
{% load staticfiles %}
{% load customtags %}
{% load tz %}
{% block css %}
    <!-- BEGIN PAGE LEVEL STYLES -->
    <link href="{% static 'common/assets/global/plugins/datatables/datatables.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'common/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'common/assets/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- END PAGE LEVEL STYLES -->
{% endblock %}

{% block contenido %}
    {% if parque.no_aerogeneradores == 0 %}
        <div class="row">
            <div class="col-md-11 col-md-offset-1">
                <h4>Por favor, ingresar la informaci&oacute;n del parque (Configuraci&oacute;n).</h4>
            </div>
        </div>
    {%  else %}
        <div class="row">
            <div class="col-md-12">
                <!-- BEGIN SAMPLE TABLE PORTLET-->
                <div class="portlet box blue-soft">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-comments"></i> Listado de Informes Diarios
                        </div>
                    </div>
                    <div class="portlet-body">
                    {% if filas|length > 0 %}
                        <table class="table table-striped table-bordered table-hover table-checkable order-column" id="tabla-dr">
                            <thead>
                                <tr>
                                    <th> # </th>
                                    <th> Fecha </th>
                                    <th> Nombre </th>
                                    <th> Actividades </th>
                                    <th> Acci&oacute;n </th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for fila in filas %}
                                <tr>
                                    <td> {{ fila.numero }}</td>
                                    <td> {{ fila.fecha }} </td>
                                    <td> DR_{{ fila.parque.codigo|upper }}_{{ fila.numero|paddingzeros:3 }} </td>
                                    <td> {{ fila.actividades }} </td>
                                    <td>
                                        <a href="{% url 'dr:reporte_dr_word' parque.slug fila.id %}" class="btn btn-circle btn-xs blue-madison">
                                            <i class="fa fa-file-word-o"></i> Reporte
                                        </a>
                                        <a href="{% url 'dr:reporte_dr_word' parque.slug fila.id %}?draft=1" class="btn btn-circle btn-xs green-soft">
                                            <i class="fa fa-file-word-o"></i> Draft
                                        </a>
                                        <a href="{% url 'dr:editar' parque.slug fila.id %}" class="btn btn-circle btn-xs yellow-saffron">
                                            <i class="fa fa-edit"></i> Editar
                                        </a>
                                        {% if perms.ncr.delete_observacion or user == observacion.created_by %}
                                        <!-- <input type="button" id="del_{{ observacion.id }}" data-target="#basic" data-toggle="modal" class="btn btn-xs btn-circle red" value="Borrar" onclick="$('#del_id').val({{ fila.id }})"/> -->
                                        <a href="#basic" id="del_{{ fila.id }}" data-toggle="modal" class="btn btn-circle btn-xs red-haze" value="Borrar" onclick="$('#del_id').val({{ fila.id }})" >
                                            <i class="fa fa-trash-o"></i> Eliminar
                                        </a>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    {% else %}
                        No existen informes diarios.
                    {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% if perms.ncr.add_observacion %}
        <div class="row">
            <div class="col-md-2">
                <a href="{% url 'dr:agregar' parque.slug %}" class="btn green-steel"> Agregar DR
                    <i class="fa fa-plus"></i>
                </a>
            </div>
        </div>
        {% endif %}
        <div class="clearfix">

        </div>

    {% endif %}

<div class="modal fade" id="basic" tabindex="-1" role="basic" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">
                    <span class="glyphicon glyphicon-exclamation-sign" style="color:rgba(255, 63, 0, 0.89);font-size:20px"></span>
                     <b>Advertencia</b> </h4>
            </div>
            <div class="modal-body">
                 <h5><b>&iquest;Desea borrar el reporte? Esto eliminará todas las actividades e imágenes.</b> </h5>
            </div>
            <div class="modal-footer">

                <form action="{% url 'dr:borrar' parque.slug %}" method="post" id="formModal">
                    {% csrf_token %}
                    <input type="hidden" name="del_id" id="del_id" value="">
                    <input type="hidden" name="back_url" id="back_url" value="">
                    <button type="button" class="btn default" data-dismiss="modal">Cancelar</button>
                    <button type="submit" id='enviarmodal' class="btn red" name="FromList">Borrar</button>
                    <!--<a href="" id='enviarmodal' class="btn btn-success success">Save Changes</a>-->
                </form>
                <!--<button type="button" id="enviarmodal" class="btn blue">Save changes</button>-->

            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

{% endblock %}

{% block javascript %}
<!-- BEGIN PAGE LEVEL PLUGINS -->
    <script src="{% static 'common/assets/global/scripts/datatable.js' %}" type="text/javascript"></script>
    <script src="{% static 'common/assets/global/plugins/datatables/datatables.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'common/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js' %}" type="text/javascript"></script>
    <script src="{% static 'common/js/tabla-dr.js' %}" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
{% endblock %}

{% block jquery %}

    $("#back_url").val(window.location.href);

{% endblock %}

dr/templates/dr/w_dr_form.html
{% load staticfiles %}
{% load customtags %}
{% load tz %}
{% load sekizai_tags %}


{% addtoblock "widget-css" %}
    <!-- BEGIN PAGE LEVEL STYLES -->
    <link href="{% static 'common/assets/global/plugins/bootstrap-select/css/bootstrap-select.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'common/assets/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'common/bootstrap-timepicker/css/bootstrap-timepicker.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- END PAGE LEVEL STYLES -->
{% endaddtoblock %}


<!-- BEGIN FORM-->
 <form action="#" class="form-horizontal form-bordered" id="form_dr" method="post">
    {% csrf_token %}
    {{ form.parque }}
    <div class="form-body">
        <div class="form-group">
            <label class="control-label col-md-3">Fecha DR:</label>
            <div class="col-md-9">
                <div class="input-group input-medium date date-picker" data-date-format="dd-mm-yyyy" data-date-show-today-button="true">
                    {{ form.fecha }}
                    <span class="input-group-btn">
                        <button class="btn default" type="button">
                            <i class="fa fa-calendar"></i>
                        </button>
                    </span>
                </div>
                <span class="help-block"> {{ form.fecha.errors }} </span>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-3">{{ form.numero.label }}</label>
            <div class="col-md-9">
                {{ form.numero }}
                <span class="help-block"> {{ form.numero.errors }} </span>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-3">{{ form.climatologia.label }}</label>
            <div class="col-md-9">
                {{ form.climatologia }}
                <span class="help-block"> {{ form.climatologia.errors }} </span>
            </div>
        </div>


        <div class="form-group">
            <label class="control-label col-md-3">{{ form.sitio.label }}:</label>
            <div class="col-md-9">
                {{ form.sitio }}
                <span class="help-block"> {{ form.sitio.errors }} </span>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-3">{{ form.actividades.label }}</label>
            <div class="col-md-9">
                {{ form.actividades }}
                <span class="help-block"> {{ form.actividades.errors }} </span>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-3">{{ form.hora_entrada.label }}</label>
            <div class="col-md-9">
                <div class="input-group">
                    {{ form.hora_entrada }}
                    <span class="input-group-btn">
                        <button class="btn default" type="button">
                            <i class="fa fa-clock-o"></i>
                        </button>
                    </span>
                </div>
                <span class="help-block"> {{ form.hora_entrada.errors }} </span>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-3">{{ form.hora_salida.label }}</label>
            <div class="col-md-9">
                <div class="input-group">
                    {{ form.hora_salida }}
                    <span class="input-group-btn">
                        <button class="btn default" type="button">
                            <i class="fa fa-clock-o"></i>
                        </button>
                    </span>
                </div>
                <span class="help-block"> {{ form.hora_salida.errors }} </span>
            </div>
        </div>

    </div>
    <div class="form-actions">
        <div class="row">
            <div class="col-md-offset-3 col-md-9">
                <button type="submit" class="btn green">
                    <i class="fa fa-save"></i> {% if editar %} Editar {% else %} Agregar {% endif %}</button>
                <a href="{{ back_url }}" class="btn default"> Volver </a>
            </div>
        </div>
    </div>
</form>


{% addtoblock "widget-javascript" %}
<!-- BEGIN PAGE LEVEL PLUGINS -->
    <script src="{% static 'common/js/moment/moment-with-locales.js' %}" type="text/javascript"></script>
    <script src="{% static 'common/assets/pages/scripts/components-bootstrap-switch.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'common/assets/global/plugins/bootstrap-select/js/bootstrap-select.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'common/assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'common/assets/global/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.es.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'common/assets/global/plugins/bootbox/bootbox.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'common/bootstrap-timepicker/js/bootstrap-timepicker.min.js' %}" type="text/javascript"></script>
    <!--
    <script src="{% static 'common/assets/pages/scripts/components-date-time-pickers.min.js' %}" type="text/javascript"></script>
    -->
    <!-- END PAGE LEVEL PLUGINS -->
{% endaddtoblock %}

{% addtoblock "widget-jquery" %}
    if (jQuery().datepicker) {
        $('.date-picker').datepicker({
            locale: "es",
            language: "es",
            rtl: App.isRTL(),
            orientation: "right",
            autoclose: true,
            showTodayButton: true,
            toolbarPlacement:"bottom",
            todayHighlight:true,
            todayBtn:"linked",

        });
        //$('body').removeClass("modal-open"); // fix bug when inline picker is used in modal
    }

    $(".timepicker").timepicker({
        template:false,
        minuteStep:5,
        showSeconds:!1,
        showMeridian:!1
    })

    /* Workaround to restrict daterange past date select: http://stackoverflow.com/questions/11933173/how-to-restrict-the-selectable-date-ranges-in-bootstrap-datepicker */

    // Workaround to fix datepicker position on window scroll
    $( document ).scroll(function(){
        $('#form_modal2 .date-picker').datepicker('place'); //#modal is the id of the modal
    });
    $('.bs-select').selectpicker({
        iconBase: 'fa',
        tickIcon: 'fa-check',
        dropupAuto: false,
    });

    //$("#form_observacion").submit(function( event ) {
    //    //alert('');
    //    //console.log($("#id_fecha_observacion").val());
    //    $("#id_fecha_revision").val($("#id_fecha_observacion").val());
    //
    //});

{% endaddtoblock %}