ControlObras/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from usuarios.views import ingresar, salir, usuario_forbidden
from django.conf.urls.static import static
from django.conf import settings


if settings.DEBUG is True:
    urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    url(r'^admin/', include('usuarios.urls',namespace='usuarios',app_name="usuarios")),
    url(r'^admin2/', admin.site.urls),
    url(r'^login/$', ingresar, {'homepage':'vista:index'}, name='ingresar'),
    url(r'^logout/$', salir, name='salir'),
    url(r'^403/$', usuario_forbidden, name='forbidden'),
    url(r'^(?P<slug>[-\w\d]+)/ncr/',include('ncr.urls', namespace='ncr', app_name="ncr")),
    url(r'^(?P<slug>[-\w\d]+)/followup/',include('fu.urls', namespace='fu', app_name="fu")),
    url(r'^(?P<slug>[-\w\d]+)/dr/',include('dr.urls', namespace='dr', app_name="dr")),
    url(r'^',include('vista.urls', namespace='vista', app_name="vista")),
]

dr/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from dr import views

urlpatterns = [
    url(r'^editar/actividad/ajax', views.actividad_ajax, name='actividad_ajax'),
    url(r'^editar/composicion/ajax', views.composicion_ajax, name='composicion_ajax'),
    url(r'^editar/(?P<dr_id>[0-9]+)/actividad/composicion/agregar', views.composicion_agregar, name='composicion_agregar'),
    url(r'^editar/(?P<dr_id>[0-9]+)/ordenar', views.dr_ordenar, name='dr_ordenar'),
    url(r'^editar/(?P<dr_id>[0-9]+)/actividad/agregar', views.actividad_agregar, name='actividad_agregar'),
    url(r'^editar/(?P<dr_id>[0-9]+)/actividad/eliminar', views.actividad_eliminar, name='actividad_eliminar'),
    url(r'^editar/(?P<dr_id>[0-9]+)/composicion/eliminar', views.composicion_eliminar, name='composicion_eliminar'),
    url(r'^editar/(?P<dr_id>[0-9]+)', views.editar, name='editar'),
    url(r'^reporte/(?P<dr_id>[0-9]+)', views.create_dr_word, name='reporte_dr_word'),
    url(r'^listado', views.listado, name='listado'),
    url(r'^agregar', views.agregar, name='agregar'),
    url(r'^borrar', views.borrar, name='borrar'),
]

usuarios/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from usuarios import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^usuarios/agregar', views.usuario_agregar, name='usuario-agregar'),
    url(r'^usuarios/(?P<usuario_id>[0-9]+)/editar', views.usuario_editar, name='usuario-editar'),
    url(r'^usuarios/borrar', views.usuario_borrar, name='usuario-borrar'),
    url(r'^usuarios/cambiar_contrasena', views.usuario_cambiarcontrasena, name='usuario-cambiarcontrasena'),
    url(r'^usuarios', views.usuarios, name='usuarios'),
]

usuarios/models.py
from django.db import models

from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import User
from vista.models import ParqueSolar

import logging
# Get an instance of a logger
logger = logging.getLogger('oritec')


# Dummy Model to create global permissions, a kind of helper.
class General(models.Model):
    dummy = models.PositiveIntegerField()

    class Meta:
        permissions = (
            ("vista", "Permiso de lectura"),
            ("revision", "Permiso de revision"),
            ("escritura", "Permiso para escribir"),
            ("create_editables", "Generar archivos editables"),
        )


class GlobalPermissionManager(models.Manager):
    def get_query_set(self):
        return super(GlobalPermissionManager, self).\
            get_query_set().filter(content_type__name='global_permission')


class GlobalPermission(Permission):
    """A global permission, not attached to a model"""
    objects = GlobalPermissionManager()

    class Meta:
        proxy = True

    def save(self, *args, **kwargs):
        ct, created = ContentType.objects.get_or_create(
            name="global_permission", app_label=self._meta.app_label
        )
        logger.debug(ct)
        self.content_type = ct
        super(GlobalPermission, self).save(*args, **kwargs)


class Usuario(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    parques = models.ManyToManyField(ParqueSolar)
    changed_pass = models.BooleanField(default=False)


class Log(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    tipo = models.IntegerField(default=0)  # 1: Add, 2: Change, 3: Delete, 0: Sin tipo
    texto = models.TextField(max_length=200)

usuarios/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import Context
from django.contrib.auth.models import User
from usuarios.models import Usuario
from django.template.context import RequestContext
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required, permission_required

from django.contrib.auth import login, authenticate, logout
from usuarios.form import EditUsuarioForm, NewUsuarioForm, ChangePasswordForm
from django.contrib.auth.models import Group
from django.contrib import messages
from vista.models import ParqueSolar
from models import Log
#Helpers
from vista.functions import *

import datetime
import logging
import os.path
logger = logging.getLogger('oritec')
#logger.setLevel(logging.DEBUG)

from usuarios.form import LoginForm

def check_password(user):
    usuario = Usuario.objects.get(user=user)
    return usuario.changed_pass

def check_permisos(user):
    usuario = Usuario.objects.get(user=user)
    if user.is_superuser:
        return True
    else:
        return False

# ========== Login ==========
def ingresar(request, homepage):
    logger.debug(homepage)
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse(homepage))
    
    form = LoginForm(request.POST or None)
    
    if request.method=='POST' and form.is_valid():
        user = form.login(request)
        if user:
            login(request, user)
            return HttpResponseRedirect(reverse(homepage))
    
    return render(request,'usuarios/login.html',
          {'form': form})

# ========== Logout ==========
def salir(request):
    logout(request)
    return HttpResponseRedirect(reverse('ingresar'))

def home(request):
    contenido = ContenidoContainer()
    contenido.user = request.user
    contenido.titulo = u'Perfil Usuario'
    contenido.subtitulo = ''
    contenido.menu = ['menu-perfil', 'menu2-dashboard']
    usuario = Usuario.objects.get(user=request.user)
    proyectos = usuario.parques.all()

    logs = Log.objects.filter(user=request.user).order_by('-created_at')[:10]
    logs_all = Log.objects.all().order_by('-created_at')[:20]
    return render(request, 'usuarios/home.html',
                  {'cont': contenido,
                   'proyectos': proyectos,
                   'logs': logs,
                   'logs_all': logs_all,
                   })

@permission_required('usuarios.add_usuario', raise_exception=True)
def usuarios(request):
    contenido = ContenidoContainer()
    contenido.user = request.user
    contenido.titulo = u'Administración de usuarios'
    contenido.subtitulo = ''
    contenido.menu = ['menu-usuarios', 'menu2-dashboard']
    users = Usuario.objects.all()
    return render(request, 'usuarios/usuarios.html',
                  {'cont': contenido,
                   'usuarios': users,
                   })

def check_permissions(usuario, perfil, proyectos=None,user_edit=None):
    user = usuario.user
    if user.is_superuser:
        return True

    group = Group.objects.get(name='Usuario 1')
    # Primer check, el unico otro usuario que puede hacer algo es el Usuario 1.
    if not group in user.groups.all():
        return False
    if perfil == 0:
        return False  # No puede crear un usuario con acceso a superusuario
    elif perfil == group.id:
        return False  # No puede crear un usuario con su mismo perfil.
    if user_edit is not None:
        if user_edit.user.is_superuser:
            return False # No puede Editar una caracteristica de un superusuario
        if group in user_edit.user.groups.all():
            return False # No puede Editar a un usuario de su mismo nivel

    if proyectos is not None:
        if user_edit is None:
            cambiados = proyectos
        else:
            eliminados = []
            old_int = user_edit.parques.all()
            old = []
            for o in old_int:
                old.append(str(o.id))
                if str(o.id) not in proyectos:
                    eliminados.append(str(o.id))
            nuevos = []
            for n in proyectos:
                if n not in old:
                    nuevos.append(n)
            cambiados = eliminados + nuevos
        posibles = []
        for p in usuario.parques.all():
            posibles.append(str(p.id))
        for c in cambiados:
            if c not in posibles:
                return False
    return True

def set_user_information(user,user_edit,form):
    if user_edit is None:
        if form.cleaned_data['perfil'] == '0':
            user_django_new = User.objects.create_superuser(form.cleaned_data['nombre'],
                                                            None,
                                                            form.cleaned_data['password'])
        else:
            user_django_new = User.objects.create_user(form.cleaned_data['nombre'],
                                                       None,
                                                       form.cleaned_data['password'])
        user_edit = Usuario(user=user_django_new)
        user_edit.save()
    else:
        user_edit.user.username = form.cleaned_data['nombre']

    user_django = user_edit.user
    if form.cleaned_data['perfil'] == '0':
        user_django.is_superuser = True
        user_edit.parques.clear()
        for parque in ParqueSolar.objects.all():
            user_edit.parques.add(parque)
    else:
        grupo = Group.objects.get(id=int(form.cleaned_data['perfil']))
        user_django.groups.clear()
        user_django.groups.add(grupo)
        user_django.is_superuser = False
        user_edit.parques.clear()
        for p_id in form.cleaned_data['proyectos']:
            parque = ParqueSolar.objects.get(id=int(p_id))
            user_edit.parques.add(parque)

    user_django.save()
    user_edit.save()

    return True

@permission_required('usuarios.add_usuario', raise_exception=True)
def usuario_editar(request, usuario_id):
    contenido = ContenidoContainer()
    contenido.user = request.user
    usuario = Usuario.objects.get(user=request.user)
    usuario_edit = Usuario.objects.get(id=usuario_id)

    contenido.titulo = u'Administración de usuarios'
    contenido.subtitulo = 'Editar usuario'
    contenido.menu = ['menu-usuarios', 'menu2-dashboard']
    form = None
    valid = False
    if request.method == 'POST':
        form = EditUsuarioForm(request.POST,usuario=usuario)
        if form.is_valid():
            proyectos_add = []
            check = check_permissions(usuario, form.cleaned_data['perfil'], proyectos=form.cleaned_data['proyectos'],user_edit = usuario_edit)
            if not check:
                messages.add_message(request, messages.ERROR, 'Usuario no tiene permisos para realizar esta acción.')
            else:
                valid = set_user_information(request.user, usuario_edit, form)
                if valid:
                    log_msg = "Se edita usuario " + usuario_edit.user.username
                    log = Log(texto=log_msg, tipo=2, user=request.user)
                    log.save()
                    messages.add_message(request, messages.SUCCESS, 'Usuario modificado con éxito!')

        if not valid:
            messages.add_message(request, messages.ERROR, 'Edición de usuario fallida.')
    if form is None:
        form = EditUsuarioForm(usuario=usuario,edit= usuario_edit)
    if valid:
        return HttpResponseRedirect(reverse('usuarios:usuarios'))
    return render(request, 'usuarios/usuario_agregar.html',
                  {'cont': contenido,
                   'form':form,
                   })

@permission_required('usuarios.add_usuario', raise_exception=True)
def usuario_agregar(request):
    contenido = ContenidoContainer()
    contenido.user = request.user
    usuario=Usuario.objects.get(user=request.user)
    contenido.titulo = u'Administración de usuarios'
    contenido.subtitulo = 'Agregar Usuario'
    contenido.menu = ['menu-usuarios', 'menu2-dashboard']

    form = None
    valid = False

    if request.method == 'POST':
        form = NewUsuarioForm(request.POST,usuario=usuario)
        if form.is_valid():
            check = check_permissions(usuario, form.cleaned_data['perfil'],
                                      proyectos=form.cleaned_data['proyectos'])
            if not check:
                messages.add_message(request, messages.ERROR, 'Usuario no tiene permisos para realizar esta acción.')
            else:
                valid = set_user_information(request.user, None, form)
                if valid:
                    log_msg = "Se agrega usuario " + form.cleaned_data['nombre']
                    log = Log(texto=log_msg, tipo=1, user=request.user)
                    log.save()
                    messages.add_message(request, messages.SUCCESS, 'Usuario agregado con éxito!')
        else:
            if '__all__' in form.errors:
                for error in form.errors['__all__']:
                    messages.add_message(request, messages.ERROR, error)

        if not valid:
            messages.add_message(request, messages.ERROR, 'No se pudo agregar usuario.')

    if form is None:
        form = NewUsuarioForm(usuario=usuario)

    if valid:
        return HttpResponseRedirect(reverse('usuarios:usuarios'))

    return render(request, 'usuarios/usuario_agregar.html',
                  {'cont': contenido,
                   'form':form,
                   })

@permission_required('usuarios.add_usuario', raise_exception=True)
def usuario_borrar(request):
    contenido = ContenidoContainer()
    contenido.user = request.user
    contenido.titulo = u'Administración de usuarios'
    contenido.subtitulo = ''
    contenido.menu = ['menu-usuarios', 'menu2-dashboard']
    if request.method == 'POST':

usuarios/templates/usuarios/header.html
{% load staticfiles %}
<!-- BEGIN HEADER -->
<div class="page-header navbar navbar-fixed-top" style="background-color: #74a1a8;">
	<!-- BEGIN HEADER INNER -->
	<div class="page-header-inner">
		<!-- BEGIN LOGO -->
		<div class="page-logo">
			<a href="/">
			<img src="{% static 'common/images/saroenfull.png' %}" alt="logo" class="logo-default" style="margin-top:7px" height="30px"/>
			</a>
		</div>
		<!-- END LOGO -->
		<!-- BEGIN RESPONSIVE MENU TOGGLER -->
		<a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
				<span></span>
		</a>
		<!-- END RESPONSIVE MENU TOGGLER -->
		<!-- BEGIN TOP NAVIGATION MENU -->
		<div class="top-menu">
			<ul class="nav navbar-nav pull-right">
				<!-- BEGIN USER LOGIN DROPDOWN -->
				<li class="dropdown dropdown-user">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
					<img alt="" class="img-circle hide1" src="{% static 'common/images/Icon-Admin.png' %}"/>
					<span class="username username-hide-on-mobile">
					    {{user|title}}
                    </span>
					<i class="fa fa-angle-down"></i>
					</a>
					<ul class="dropdown-menu">

						<!--<li>
							<a href="extra_lock.html">
							<i class="icon-lock"></i> Bloquear pantalla </a>
						</li>-->
                        <li>
							<a href="{% url 'usuarios:home' %}">
							<i class="icon-user"></i> Mi perfil </a>
						</li>
						<li>
							<a href="{% url 'salir' %}">
							<i class="icon-key"></i> Salir </a>
						</li>
					</ul>
				</li>
				<!-- END USER LOGIN DROPDOWN -->
				<!-- BEGIN QUICK SIDEBAR TOGGLER -->
				<!--<li class="dropdown dropdown-quick-sidebar-toggler">
					<a href="javascript:;" class="dropdown-toggle">
					<i class="icon-logout"></i>
					</a>
				</li>-->
				<!-- END QUICK SIDEBAR TOGGLER -->
			</ul>
		</div>
		<!-- END TOP NAVIGATION MENU -->
	</div>
	<!-- END HEADER INNER -->
</div>
<!-- END HEADER -->

usuarios/templates/usuarios/sidebar.html
{% load staticfiles %}
{% load customtags %}

<!-- BEGIN SIDEBAR -->
	<div class="page-sidebar-wrapper">
		<!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
		<!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
		<div class="page-sidebar navbar-collapse collapse">
			<!-- BEGIN SIDEBAR MENU -->
			<!-- DOC: Apply "page-sidebar-menu-light" class right after "page-sidebar-menu" to enable light sidebar menu style(without borders) -->
			<!-- DOC: Apply "page-sidebar-menu-hover-submenu" class right after "page-sidebar-menu" to enable hoverable(hover vs accordion) sub menu mode -->
			<!-- DOC: Apply "page-sidebar-menu-closed" class right after "page-sidebar-menu" to collapse("page-sidebar-closed" class must be applied to the body element) the sidebar sub menu mode -->
			<!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
			<!-- DOC: Set data-keep-expand="true" to keep the submenues expanded -->
			<!-- DOC: Set data-auto-speed="200" to adjust the sub menu slide up/down speed -->
			<ul class="page-sidebar-menu page-header-fixed " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200" style="padding-top: 20px">
				<!-- DOC: To remove the sidebar toggler from the sidebar you just need to completely remove the below "sidebar-toggler-wrapper" LI element -->
				
				<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
				<li class="sidebar-toggler-wrapper">
                    <div class="sidebar-toggler">
                        <span></span>
                    </div>
                </li>
				<!-- END SIDEBAR TOGGLER BUTTON -->
                &nbsp;
				<!--<li class="start ">-->

                <li class="nav-item" id="menu-perfil">
					<a href="{% url 'usuarios:home' %}" class="nav-link nav-toggle">
						<i class="icon-home"></i>
						<span class="title">Perfil Usuario</span>
					</a>
                </li>

                <li class="nav-item" id="menu-contrasena">
					<a href="{% url 'usuarios:usuario-cambiarcontrasena' %}" class="nav-link nav-toggle">
						<i class="icon-key"></i>
						<span class="title">Cambiar Contraseña</span>
					</a>
                </li>
                {% if perms.usuarios.add_usuario %}
                <li class="nav-item" id="menu-usuarios">
					<a href="{% url 'usuarios:usuarios' %}" class="nav-link nav-toggle">
						<i class="icon-users"></i>
						<span class="title">Usuarios</span>
					</a>
				</li>
                {% endif %}
                <li class="nav-item" id="menu-sistema">
					<a href="/" class="nav-link nav-toggle">
						<i class="icon-arrow-left"></i>
						<span class="title">Volver al Sistema</span>
					</a>
                </li>

			</ul>
			<!-- END SIDEBAR MENU -->
		</div>
	</div>
	<!-- END SIDEBAR -->

usuarios/templates/usuarios/usuarios.html
{% extends "usuarios/base.html" %}
{% load staticfiles %}
{% load customtags %}
{% load tz %}
{% block css %}
    <!-- BEGIN PAGE LEVEL STYLES -->
    <link href="{% static 'common/assets/global/plugins/datatables/datatables.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'common/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css' %}" rel="stylesheet" type="text/css" />

    <!-- END PAGE LEVEL STYLES -->
{% endblock %}

{% block contenido %}

    <div class="row">
            <div class="col-md-12">
                <a href="{% url 'usuarios:usuario-agregar'%}" class="btn btn-sm green-steel">Agregar Usuario</a>
            </div>
        </div>
    <p></p>
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN SAMPLE TABLE PORTLET-->
            <div class="portlet box blue-soft">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-comments"></i> Listado de usuarios
                    </div>
                </div>
                <div class="portlet-body">
                {% if usuarios|length > 0 %}
                    <table class="table table-striped table-bordered table-hover" id="tabla-usuarios">
                        <thead>
                            <tr>
                                <th> Usuario </th>
                                <th> Perfil </th>
                                <th> Proyectos </th>
                                <th> Acci&oacute;n </th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for usuario in usuarios %}
                            <tr>
                                <td> {{ usuario.user.username }} </td>
                                <td>{% if usuario.user.is_superuser %} Administrador {% else %} {{ usuario.user|get_group }} {% endif %}</td>
                                <td>{% if usuario.user.is_superuser %} Todos {% else %} {% for parque in usuario.parques.all %}{% if forloop.first %}{{ parque.nombre }}{% else %}, {{ parque.nombre }}{% endif %}{% endfor %}  {% endif %}</td>
                                <td>
                                    {% if cont.user|check_user_permissions:usuario %}
                                    <a href="{% url 'usuarios:usuario-editar' usuario.id %}" class="btn btn-xs btn-circle green-haze">Editar</a>
                                    {% endif %}
                                    {% if cont.user.is_superuser %}
                                    <input type="button" id="del_usuario{{ usuario.id }}" data-target="#basic" data-toggle="modal" class="btn btn-xs btn-circle red" value="Eliminar" onclick="$('#del_id').val({{ usuario.id }})"/>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    No existen usuarios.
                {% endif %}
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="basic" tabindex="-1" role="basic" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                    <h4 class="modal-title">
                        <span class="glyphicon glyphicon-exclamation-sign" style="color:rgba(255, 63, 0, 0.89);font-size:20px"></span>
                         <b>Advertencia</b> </h4>
                </div>
                <div class="modal-body">
                     <h5><b>&iquest;Seguro que desea eliminar al usuario?</b> </h5>
                </div>
                <div class="modal-footer">

                    <form action="{% url 'usuarios:usuario-borrar' %}" method="post" id="formModal">
                        {% csrf_token %}
                        <input type="hidden" name="del_id" id="del_id" value="">
                        <input type="hidden" name="back_url" id="back_url" value="">
                        <button type="button" class="btn default" data-dismiss="modal">Cancelar</button>
                        <button type="submit" id='enviarmodal' class="btn red" name="FromList">Borrar</button>
                        <!--<a href="" id='enviarmodal' class="btn btn-success success">Save Changes</a>-->
                    </form>
                    <!--<button type="button" id="enviarmodal" class="btn blue">Save changes</button>-->

                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>

{% endblock %}

{% block javascript %}
<!-- BEGIN PAGE LEVEL PLUGINS -->
    <script src="{% static 'common/assets/global/scripts/datatable.js' %}" type="text/javascript"></script>
    <script src="{% static 'common/assets/global/plugins/datatables/datatables.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'common/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js' %}" type="text/javascript"></script>
    <script src="{% static 'common/assets/global/plugins/jquery-multi-select/js/jquery.multi-select.js' %}" type="text/javascript"></script>

    <script src="{% static 'common/js/tabla-usuarios.js' %}" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
{% endblock %}

{% block jquery %}



{% endblock %}